name: tabdila
description: دستیار هوشمند شما - مجموعه ابزارهای کاربردی و تبدیلات
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI & Icons
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Network
  http: ^1.1.0
  dio: ^5.4.0
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  image_picker: ^1.0.5
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0
  pdf: ^3.10.7
  image: ^4.1.3
  
  # Charts
  fl_chart: ^0.65.0
  
  # Animations
  animations: ^2.0.8
  shamsi_date: ^1.1.1
  file_picker: ^10.3.10
  google_mlkit_text_recognition: ^0.15.1
  printing: ^5.14.2
  flutter_colorpicker: ^1.1.0
  signature: ^5.5.0
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - content/ghazal/
  
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300

